name: Release and Publish

run-name: Release and Publish

on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    name: Release
    uses: DiogoAbu/workflows/.github/workflows/reusable_release.yml@main
    permissions:
      contents: write
    with:
      should_release_command: 'yarn should-release-it'
      after_install_command: |
        yarn lint
        yarn typecheck
    secrets:
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      release_token: ${{ secrets.RELEASE_TOKEN }}
      checkout_token: ${{ secrets.RELEASE_TOKEN }}
